Решение для 5 задачи
fyoy/LevelUp-Hometasks pull request #2
Opened 2023-02-23 12:13 UTC by fyoy

2023-02-23 12:18 UTC, fyoy commented
<img width="661" alt="image" src="https://user-images.githubusercontent.com/85868130/220903630-02f5f53d-b825-414f-95d2-59c2f1414432.png">

2023-02-26 14:16 UTC, avchirkin requested changes
В целом, задача решена, но можно снизить когнитивную сложность основного рабочего метода

2023-02-26 14:16 UTC, avchirkin commented on Lesson5/StringExt.cs
> +
Лишняя пустая строка

2023-02-26 14:16 UTC, avchirkin commented on Lesson5/StringExt.cs
> +                if ((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || c == ' ')
Тут можно инвертировать логику if, чтобы уменьшить вложенность блоков. Если НЕ этот иф, то идём дальше по циклу.

2023-02-26 14:16 UTC, avchirkin commented on Lesson5/StringExt.cs
> +                        if (!(c == ' ' && c == sb[sb.Length - 1]))
Для обращения к последнему элементу массива можно использовать синтаксис sb[^1]

2023-02-26 14:16 UTC, avchirkin commented on Lesson5/StringExt.cs
> +                        if (!(c == ' ' && c == sb[sb.Length - 1]))
А для проверки на пробел - char.IsWhitespace(c)

2023-02-26 14:16 UTC, avchirkin commented on Lesson5/StringExt.cs
> +
Лишняя пустая строка

2023-02-26 19:40 UTC, fyoy commented
1. Изменил в if проверку на IsLetterorDigit
2. Убрал лишние переносы

2023-03-02 16:11 UTC, merged