Решение для 6-й задачи
fyoy/LevelUp-Hometasks pull request #3
Opened 2023-02-23 15:11 UTC by fyoy

<img width="696" alt="image" src="https://user-images.githubusercontent.com/85868130/220947217-963ac146-35a6-46db-8c37-0249e9c3b2db.png">

2023-02-26 14:47 UTC, avchirkin requested changes
Нужно причесать некоторые модели и местами поменять типы данных в колонках

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Clients.sql
> +	[Email] [nchar](255) NULL,
Лучше nvarchar, и можно поменьше

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Clients.sql
> +	[DeliveryAddress] [nchar](255) NOT NULL,
nvarchar, и тут наоборот желательно побольше, так как адрес может быть очень длинным

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/OrderStatuses.sql
> +	[Value] ASC
Лучше добавлять ID даже в случае простых таблиц-словарей, чтобы использовать эти ID как ключи. Иначе каждая таблица, которая использует OrderStatus, вместо интового/гуидного идентификатора будет вынуждена хранить весь Value, что некорректно с точки зрения нормализации данных

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Orders.sql
> +	[OrderStatus] [nchar](50) NOT NULL,
Дублирование достаточно тяжёлых данных (см. замечание к таблице статусов)

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/OrderStatuses.sql
> +	[Value] ASC
Либо, как вариант, сделать само Value максимально простым значением - например, tinyint, а текстовую расшифровку оставить для колонки Description

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Prices.sql
> +	[DateTime] [nchar](10) NOT NULL,
datetime2

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Shipments.sql
> +	[DepartureDate] [datetime] NOT NULL,
datetime2 тут и ниже

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Shipments.sql
> +	[DepartureDate] [datetime] NOT NULL,
Кстати, а почему две даты? Суть этой таблицы - хранение оприходований на склад самого магазина. Кажется, что можно обойтись датой отгрузки?

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Shipments.sql
> +	[Amount] [int] NOT NULL,
Лучше число с плавающей точкой, есть весовые товары

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Shipments.sql
> +ALTER TABLE [dbo].[Shipments]  WITH CHECK ADD  CONSTRAINT [FK_Shipments_Stocks] FOREIGN KEY([StockId])
Не хватает внешнего ключа на таблицу StockKeepingUnits

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/ShopItemCategories.sql
> +	[Name] [nchar](10) NOT NULL,
Название категории лучше сделать чуть длиннее, сейчас ограничение очень жёсткое

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/ShopItemCategories.sql
> +	[Name] [nchar](10) NOT NULL,
И nvarchar вместо nchar

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/ShopItemCategories.sql
> +	[Description] [nchar](10) NULL,
То же самое с Description

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/ShopItem.sql
> +	[SkuId] [nchar](255) NOT NULL,
В таком контексте, всё же, больше подойдёт термин NomenclatureNumber

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/ShopItem.sql
> +	[SkuId] [nchar](255) NOT NULL,
nvarchar

2023-02-26 14:47 UTC, avchirkin commented on Lesson6/Stocks.sql
> +	[Name] [nchar](255) NOT NULL,
nchar лучше использовать в случаях, когда данные +- одного размера. В колонках с названиями, описаниями и прочим непредсказуемым с точки зрения размера содержимым лучше использовать nvarchar

2023-02-26 20:13 UTC, fyoy commented
1. Изменил nchar на nvarchar
2. Изменил datetime на datetime2
3. Добавил недостающие внешние ключи для Sku в Shipments и ShopItems.

2023-03-01 20:38 UTC, avchirkin approved these changes
Не забудь добавить FK по замечанию

2023-03-01 20:38 UTC, avchirkin commented on Lesson6/Prices.sql
> +) ON [PRIMARY]
Нужен FK на таблицу ShopItems

2023-03-02 16:11 UTC, merged