Задание №9
fyoy/LevelUp-Hometasks pull request #5
Opened 2023-03-08 13:57 UTC by fyoy

<img width="732" alt="image" src="https://user-images.githubusercontent.com/85868130/223731548-03d5f674-99f1-4525-998c-28f5cd1f8382.png">

2023-03-12 19:35 UTC, avchirkin commented on Lesson9/DeliveryAddressBuilder.cs
> +    public class DeliveryAddressBuilder
Кроме форматирования, вопросов нет. Добавить пустые строки между методами для лучшей читаемости и удалить лишние пустые строки внизу - и будет хорошо

2023-03-12 19:35 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
> +        public delegate void NumberEneteredEventHandler(object sender);
Entered - очепятка

2023-03-12 19:36 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
> +                if (!string.IsNullOrEmpty(value))
Можно сразу int.TryParse

2023-03-12 19:37 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
> +        public EventListener(NumberProcessor eventGenerator, int listenerId)
Лучше вынести в отдельный файл

2023-03-12 19:42 UTC, avchirkin requested changes
В целом, ок, но сам вызов события нужно спрятать внутрь NumberProcessor'а и листенерам прокидывать только сам массив с числами

2023-03-12 19:42 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
> +            if(_listenerId == 1)
Это должны быть два разных листенера - один, получая событие, складывает числа, другой инвертирует массив

2023-03-12 19:42 UTC, avchirkin commented on Lesson9/Program.cs
> +now.RaiseEvent();
Вот здесь, в отличии от примера из песочницы, лучше сделать метод RaiseEvent приватным и дёргать его, когда NumberProcessor собрал массив.

2023-03-14 18:14 UTC, fyoy commented
"В целом, ок, но сам вызов события нужно спрятать внутрь NumberProcessor'а и листенерам прокидывать только сам массив с числами"
- Попробовал добавить вызов события в конструкторе, но тогда событие поднималось раньше, чем могли бы быть подписаны слушатели.

2023-03-15 19:42 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
>          public List<int>? numbers = new();
Всё ещё публичное поле вместо приватного

2023-03-15 19:43 UTC, avchirkin commented on Lesson9/NumberProcessor.cs
>              NumberReceivedEvent?.Invoke(this);
Не пробрасывается массив чисел вместе с вызовом ивента

2023-03-15 19:44 UTC, avchirkin commented on Lesson9/Program.cs
>  string numbers = Console.ReadLine() ?? string.Empty;
input или numbersString лучше отражают суть. numbers появятся позже

2023-03-16 19:35 UTC, fyoy commented
Думаю в этот раз я правильно сделал.

2023-04-05 17:33 UTC, merged